### ISSUE TITLE
Cannot read properties of undefined 

### ISSUE THREAD

**Issue by crunchip77** [iobroker-community-adapters/ioBroker.logparser#46]
seit dem upgrade von v1.1.0 auf v1.2.3 bekommen ich folgende Meldung
`
<html>
<body>

2023-03-01 00:00:01.003 - error: logparser.0 (2084326) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-03-01 00:00:01.011 - error: logparser.0 (2084326) unhandled promise rejection: Cannot read properties of undefined (reading 'objArrayGetObjByVal')
2023-03-01 00:00:01.032 - error: logparser.0 (2084326) TypeError: Cannot read properties of undefined (reading 'objArrayGetObjByVal')
at updateTodayYesterday (/opt/iobroker/node_modules/iobroker.logparser/main.js:196:26)
at Timeout. (/opt/iobroker/node_modules/iobroker.logparser/main.js:179:4)
at listOnTimeout (node:internal/timers:569:17)
at processTimers (node:internal/timers:512:7)
2023-03-01 00:00:01.033 - error: logparser.0 (2084326) Cannot read properties of undefined (reading 'objArrayGetObjByVal')

</body>
</html>
<html>
<body>

2023-03-01 00:00:01.336 - info: logparser.0 (2084326) cleaned everything up...
--
2023-03-01 00:00:01.337 - info: logparser.0 (2084326) terminating
2023-03-01 00:00:01.339 - warn: logparser.0 (2084326) Terminated (UNCAUGHT_EXCEPTION): Without reason

</body>
</html>
2023-03-01 00:00:02.843 - info: logparser.0 (2084326) terminating with timeout
<html>
<body>

2023-03-01 00:00:08.142 - error: host.IoBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
--
2023-03-01 00:00:08.143 - error: host.IoBroker Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'objArrayGetObjByVal')
2023-03-01 00:00:08.143 - error: host.IoBroker Caught by controller[0]: at updateTodayYesterday (/opt/iobroker/node_modules/iobroker.logparser/main.js:196:26)
2023-03-01 00:00:08.144 - error: host.IoBroker Caught by controller[0]: at Timeout. (/opt/iobroker/node_modules/iobroker.logparser/main.js:179:4)
2023-03-01 00:00:08.144 - error: host.IoBroker Caught by controller[0]: at listOnTimeout (node:internal/timers:569:17)
2023-03-01 00:00:08.144 - error: host.IoBroker Caught by controller[0]: at processTimers (node:internal/timers:512:7)
2023-03-01 00:00:08.145 - error: host.IoBroker instance system.adapter.logparser.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-01 00:00:08.146 - info: host.IoBroker Restart adapter system.adapter.logparser.0 because enabled

</body>
</html>
2023-03-01 00:00:43.863 - info: logparser.0 (2683336) starting. Version 1.2.3 in /opt/iobroker/node_modules/iobroker.logparser, node: v18.14.1, js-controller: 4.0.24`

**Comment by ciddi89** [comment]
Hi @crunchip77 
Hast du unter parser rules(filter) Sachen eingetragen? Scheint so als würde da bei dir nichts drin stehen.

**Comment by ciddi89** [comment]
Kannst du mal die Github version installieren (Experten Modus, Katze, Link einfügen) Und mir dann schreiben was er dann sagt? 
Ich danke dir schon mal

**Comment by crunchip77** [comment]
@ciddi89 mach ich

**Comment by crunchip77** [comment]
@ciddi89 
`<html>
<body>


logparser.0 | 2023-03-02 00:00:44.669 | info | starting. Version 1.2.3 (non-npm: iobroker-community-adapters/ioBroker.logparser#ec5fbdf0686701a9003b69b992bf5fc7e1c42a7d) in /opt/iobroker/node_modules/iobroker.logparser, node: v18.14.1, js-controller: 4.0.24
-- | -- | -- | --
host.IoBroker | 2023-03-02 00:00:39.130 | info | instance system.adapter.logparser.0 started with pid 3303536
host.IoBroker | 2023-03-02 00:00:36.542 | info | instance system.adapter.ical.0 terminated with code 0 (NO_ERROR)
host.IoBroker | 2023-03-02 00:00:29.512 | info | instance system.adapter.feiertage.0 terminated with code 0 (NO_ERROR)
host.IoBroker | 2023-03-02 00:00:12.672 | info | instance system.adapter.unifi.0 started with pid 3303318
host.IoBroker | 2023-03-02 00:00:12.322 | info | instance system.adapter.feiertage.0 started with pid 3303311
host.IoBroker | 2023-03-02 00:00:08.430 | info | Restart adapter system.adapter.logparser.0 because enabled
host.IoBroker | 2023-03-02 00:00:08.429 | error | instance system.adapter.logparser.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.IoBroker | 2023-03-02 00:00:08.429 | error | Caught by controller[0]: at processTimers (node:internal/timers:512:7)
host.IoBroker | 2023-03-02 00:00:08.428 | error | Caught by controller[0]: at listOnTimeout (node:internal/timers:569:17)
host.IoBroker | 2023-03-02 00:00:08.427 | error | Caught by controller[0]: at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.logparser/main.js:179:4)
host.IoBroker | 2023-03-02 00:00:08.427 | error | Caught by controller[0]: at updateTodayYesterday (/opt/iobroker/node_modules/iobroker.logparser/main.js:196:26)
host.IoBroker | 2023-03-02 00:00:08.426 | error | Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'objArrayGetObjByVal')
host.IoBroker | 2023-03-02 00:00:08.425 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.IoBroker | 2023-03-02 00:00:06.530 | info | Restart adapter system.adapter.unifi.0 because enabled
host.IoBroker | 2023-03-02 00:00:06.529 | info | instance system.adapter.unifi.0 scheduled normal terminated and will be restarted on schedule.
host.IoBroker | 2023-03-02 00:00:06.361 | info | instance system.adapter.ical.0 started with pid 3303287
logparser.0 | 2023-03-02 00:00:02.316 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
logparser.0 | 2023-03-02 00:00:02.314 | info | terminating
logparser.0 | 2023-03-02 00:00:02.312 | info | cleaned everything up...
logparser.0 | 2023-03-02 00:00:01.021 | error | Cannot read properties of undefined (reading 'objArrayGetObjByVal')
logparser.0 | 2023-03-02 00:00:01.020 | error | TypeError: Cannot read properties of undefined (reading 'objArrayGetObjByVal') at updateTodayYesterday (/opt/iobroker/node_modules/iobroker.logparser/main.js:196:26) at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.logparser/main.js:179:4) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7)
logparser.0 | 2023-03-02 00:00:01.012 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'objArrayGetObjByVal')
logparser.0 | 2023-03-02 00:00:01.002 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>`

**Comment by ciddi89** [comment]
Ist das immer um 0 Uhr? Aber sonst läuft der Adapter oder?

**Comment by ciddi89** [comment]
Ok den Fehler spuckt er nicht mehr aus, das ist erstmal mit der GitHub version beseitigt. Muss mir das aber noch mal genauer angucken, daher bitte diesen thread nicht schliessen. :)

**Comment by crunchip77** [comment]
> Ist das immer um 0 Uhr? Aber sonst läuft der Adapter oder?

ja


> Kannst das gerne noch mal mit der Katzen Version testen.

mach ich

**Comment by crunchip77** [comment]
@ciddi89 Log blieb heute sauber , keine Fehlermeldung

**Comment by mcm1957** [comment]
Sollte damit oin 2.0.0 behoben sein

**Comment by ciddi89** [comment]
Fixed in 2.1.0
